### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: sink must not be a boolean

### ISSUE THREAD

**Issue by Smythu** [masihyeganeh/YoutubeDownloader#37]
I get this error while trying to download a video.

`Fatal error: Uncaught InvalidArgumentException: sink must not be a boolean in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:378 Stack trace: #0 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(273): GuzzleHttp\Client->applyOptions(Object(GuzzleHttp\Psr7\Request), Array) #1 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(99): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array) #2 /var/www/html/vendor/masih/youtubedownloader/Masih/YoutubeDownloader/YoutubeDownloader.php(838): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array) #3 /var/www/html/vendor/masih/youtubedownloader/Masih/YoutubeDownloader/YoutubeDownloader.php(1039): Masih\YoutubeDownloader\YoutubeDownloader->downloadFile('https://r3---sn...', '../videos//dead...', Object(Closure), Object(Closure)) #4 /var/www/html/vendor/masih/youtubedownloader/Masih/YoutubeDownloader/YoutubeDownloader.php(914): Masih\YoutubeDownloader\YoutubeDownloader->downloadFull('https://r3---sn...', '../videos//dead...', false) #5 /var/www/ in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 378`

any ideas? what does it mean?

**Comment by Smythu** [comment]
solved:
i had to give my videos folder chmod 777
