### ISSUE TITLE
Probelm with downloading enctypted videos

### ISSUE THREAD

**Issue by zibra** [masihyeganeh/YoutubeDownloader#60]
I'm getting error when trying to download movie:
`https://www.youtube.com/watch?v=Tlhxqs3KjtE`

Error log:
```
V8JsScriptException: base.js:3725: TypeError: window.WeakMap is not a constructor in \vendor\masih\youtubedownloader\Masih\YoutubeDownloader\JsDecoder.php:205 Stack trace: 
#0 \vendor\masih\youtubedownloader\Masih\YoutubeDownloader\JsDecoder.php(205): V8Js->executeString('var _yt_player=...', 'base.js') 
#1 \vendor\masih\youtubedownloader\Masih\YoutubeDownloader\JsDecoder.php(161): Masih\YoutubeDownloader\JsDecoder->v8jsDecrypt('8DA045D3120EB4E...') 
#2 \vendor\masih\youtubedownloader\Masih\YoutubeDownloader\YoutubeDownloader.php(372): Masih\YoutubeDownloader\JsDecoder->decode('8DA045D3120EB4E...') 
#3 \vendor\masih\youtubedownloader\Masih\YoutubeDownloader\YoutubeDownloader.php(556): Masih\YoutubeDownloader\YoutubeDownloader->decryptSignature('8DA045D3120EB4E...', Object(Masih\YoutubeDownloader\JsDecoder)) 
#4 \vendor\masih\youtubedownloader\Masih\YoutubeDownloader\YoutubeDownloader.php(908): Masih\YoutubeDownloader\YoutubeDownloader->getVideoInfo(true) 
#5 \app\Helpers\YoutubeDownloaderHelper.php(20): Masih\YoutubeDownloader\YoutubeDownloader->download() 
#6 \app\Http\Controllers\MovieController.php(293): App\Helpers\YoutubeDownloaderHelper->download('https://www.you...', 991) 
...
```

**Comment by zibra** [comment]
I've solved my problem. I was missing `cache` folder. To be honest I was missing it for a long time, but only now this caused me problem on this video.
